name: my-workflow

on: [push]

jobs:
  my-first-workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    defaults:
      run:
        working-directory: ..
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
        working-directory: frontend
      - run: echo "HG LOGS ${{github.event_name}} ${{runner.os}} ${{github.ref}} ${{github.repository}} ${{job.status}}"
      - run: npm install
        working-directory: frontend
      - run: npm run lint
        working-directory: frontend
      - run: npm run test
        working-directory: frontend
      - run: npm run build
        working-directory: frontend
